services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.web.dev
    ports:
      - "5173:5173"
    volumes:
      - ../:/web
      - /web/node_modules
    command: sh -c "yarn install && yarn vite"
