FROM node:22-alpine

WORKDIR /web

COPY ../../package.json ../../yarn.lock ./
COPY ../../vite.config.ts ./
COPY ../../tsconfig.json ./
COPY ../../public ./public
COPY ../../src ./src
COPY ../../index.html ./

RUN yarn install

EXPOSE 5173

CMD ["yarn", "vite"]
